HUBOT_AMQP_USER=$HUBOT_AMQP_USER \
HUBOT_AMQP_PASSWORD=$HUBOT_AMQP_PASSWORD \
HUBOT_AMQP_URL=$HUBOT_AMQP_URL \
HUBOT_WORMHOLE_ROUTING_KEY=$HUBOT_WORMHOLE_ROUTING_KEY \
HUBOT_WORMHOLE_BINDING_KEYS=$HUBOT_WORMHOLE_BINDING_KEYS \
HUBOT_WORMHOLE_IN=$HUBOT_WORMHOLE_IN \
HUBOT_WORMHOLE_OUT=$HUBOT_WORMHOLE_OUT \
HUBOT_EXHALE_ROOM=$HUBOT_EXHALE_ROOM \
HUBOT_SLACK_TOKEN=$HUBOT_SLACK_TOKEN \
./bin/hubot --adapter slack --disable-httpd
